### ISSUE TITLE
how connect gopro hero 9 to yolov5?

### ISSUE THREAD

**Issue by savinasz** [KonradIT/gopro-firmware-archive#2]
i want to make an object detection with yolov5 and gopro hero 9 black for the camera, but i don't know how to connect the gopro to yolo. i have tried https://mteasylearn.com/blog/yolov5-object-detection-from-gopro-camera this. but its not worked for gopro hero 9.  please help me please please please........

**Comment by KonradIT** [comment]
Out of scope for this repo.

Learn how to [ask questions](http://www.catb.org/~esr/faqs/smart-questions.html).
